<?xml version="1.1" encoding="UTF-8" ?>
<!DOCTYPE sla-profile [

<!ELEMENT sla-profile (description?, sla-threshold*)>
<!ATTLIST sla-profile
    uid CDATA #REQUIRED
    uniqueKey CDATA #REQUIRED>

<!ELEMENT description (#PCDATA)>
	
<!ELEMENT sla-threshold ((threshold-condition )*)>
<!ATTLIST sla-threshold
	uid CDATA #REQUIRED
	percent CDATA #IMPLIED
	identifier CDATA #REQUIRED
	enabled CDATA #REQUIRED
	family CDATA #REQUIRED>

<!ELEMENT threshold-condition (#PCDATA)>
<!ATTLIST threshold-condition
    severity CDATA #REQUIRED
    durationKind CDATA #REQUIRED
    durationNumber CDATA #REQUIRED
    operator CDATA #REQUIRED
    valueMin CDATA #REQUIRED
    valueMax CDATA #REQUIRED>

]>
<sla-profile name="IDL" uid="508f0b4d-2bf4-409f-9dba-5dabac92a40a">
<description/>
<sla-threshold enabled="false" family="PER_RUN" identifier="AVERAGE_REQUEST_RESPONSE_TIME" percent="1" uid="bbb1f31d-7fbb-4652-847e-6e1b248d6896">
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="HIGH" valueMax="Infinity" valueMin="0.5"/>
</sla-threshold>
<sla-threshold enabled="true" family="PER_RUN" identifier="AVERAGE_PAGE_RESPONSE_TIME" percent="1" uid="bed42464-eafd-4cbd-8e8d-3ff2a34b73c0">
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="HIGH" valueMax="Infinity" valueMin="0.5"/>
</sla-threshold>
<sla-threshold enabled="true" family="PER_RUN" identifier="AVERAGE_CONTAINER_RESPONSE_TIME" percent="1" uid="f22eaa92-fc26-46a9-b7bf-11623368ba41">
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="HIGH" valueMax="Infinity" valueMin="0.5"/>
</sla-threshold>
<sla-threshold enabled="false" family="PER_RUN" identifier="PERCENTILE_CONTAINER_RESPONSE_TIME" percent="1" uid="430b1407-385a-4879-94c4-b5c9a6174b2c"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="AVERAGE_HITS_PER_SECOND" percent="1" uid="e12913d1-3438-4afb-9023-645cffb566db"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="AVERAGE_THROUGHPUT_PER_SECOND" percent="1" uid="f0754f6e-2738-4d74-928d-ff46d3bb5836"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="TOTAL_ERRORS" percent="1" uid="82022b22-802f-4717-b744-55213b9bc5c9"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="TOTAL_HITS" percent="1" uid="538f0924-f49a-414c-8c77-dc8c6fb405c4"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="TOTAL_THROUGHPUT" percent="1" uid="e4df4770-ec8f-408a-9da8-444a43dea362"/>
<sla-threshold enabled="true" family="PER_RUN" identifier="ERROR_PERCENTILE" percent="1" uid="a95aeddf-4e23-4d7d-abfe-b13c3e9263af">
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="LOW" valueMax="Infinity" valueMin="4.0"/>
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="HIGH" valueMax="Infinity" valueMin="5.0"/>
</sla-threshold>
<sla-threshold enabled="true" family="PER_TIME_INTERVAL" identifier="AVERAGE_RESPONSE_TIME" percent="1" uid="8f07f5d8-8619-4452-ab98-ec0e8d746239">
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="HIGH" valueMax="Infinity" valueMin="0.5"/>
</sla-threshold>
<sla-threshold enabled="false" family="PER_TIME_INTERVAL" identifier="AVERAGE_HITS_PER_SECOND" percent="1" uid="35355c2c-cbfd-4f7b-8a9e-51b715f414b6"/>
<sla-threshold enabled="false" family="PER_TIME_INTERVAL" identifier="AVERAGE_THROUGHPUT_PER_SECOND" percent="1" uid="911c3b94-3007-4e7a-b179-ec3b9d02f14b"/>
<sla-threshold enabled="false" family="PER_TIME_INTERVAL" identifier="ERRORS_PER_SECOND" percent="1" uid="f6bd7564-8a0b-41a4-8da4-37cbca6f96de"/>
<sla-threshold enabled="true" family="PER_TIME_INTERVAL" identifier="ERROR_PERCENTILE" percent="1" uid="d111f680-c163-4ff4-9ca6-7056fa998f9a">
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="HIGH" valueMax="Infinity" valueMin="5.0"/>
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="LOW" valueMax="Infinity" valueMin="4.0"/>
</sla-threshold>
</sla-profile>
